// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDznUAbEPzy5TO45EpqchwghkyKATgEZfA',
    appId: '1:209859165632:web:a9226dccef97f9e69b9c25',
    messagingSenderId: '209859165632',
    projectId: 'strayfriends-utm',
    authDomain: 'strayfriends-utm.firebaseapp.com',
    storageBucket: 'strayfriends-utm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTzDjscrlNCjKVLt2UKGtax2FbMyMkQ3o',
    appId: '1:209859165632:android:103acc10c17e79159b9c25',
    messagingSenderId: '209859165632',
    projectId: 'strayfriends-utm',
    storageBucket: 'strayfriends-utm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNmW5psM8Z3xCNkvlSNJYIxumgddQP7w',
    appId: '1:209859165632:ios:37a0e50ea6ee660e9b9c25',
    messagingSenderId: '209859165632',
    projectId: 'strayfriends-utm',
    storageBucket: 'strayfriends-utm.firebasestorage.app',
    iosBundleId: 'my.utm.strayfriends.strayfriends',
  );
}
