import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Typed access to .env values. Loaded once by [Env.load] in main().
///
/// Storage + Auth + Firestore config live in `firebase_options.dart`
/// (generated by FlutterFire), NOT here. This file is only for
/// runtime-loaded secrets that aren't part of the Firebase config —
/// currently the Sprint 4 payment gateway keys.
class Env {
  Env._();

  /// Loads .env if present. Tolerant of a missing file so the app still
  /// boots on a fresh clone without payment keys — the only consumers
  /// (payment gateway, Sprint 4) read nullable getters below.
  static Future<void> load() async {
    try {
      await dotenv.load(fileName: '.env');
    } catch (_) {
      // No .env on this machine yet — fine. Firebase config is compiled
      // into firebase_options.dart; nothing here is required at startup.
    }
  }

  // Sprint 2/4 payment gateway placeholders (NAD-21). Nullable —
  // PaymentService runs in simulation mode when these are absent.
  static String? get stripePublishableKey =>
      dotenv.env['STRIPE_PUBLISHABLE_KEY'];
  static String? get billplzApiKey => dotenv.env['BILLPLZ_API_KEY'];
}
